import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import * as lucide from 'lucide';

// Emits `src/app/icon-paths.ts` from the installed Lucide package, so the app's icon
// geometry is upstream Lucide rather than hand-drawn markup that drifts per screen.
// `lucide` is a devDependency: only the generated path strings reach the bundle.
//
// To add an icon, put its Lucide name in ICONS below and run `npm run icons`.
// Names are Lucide's own, from https://lucide.dev/icons - keeping them unaliased is what
// makes "which icon is this" answerable without reading the renderer.

const ICONS = [
  'arrow-down-left',
  'arrow-up-right',
  'award',
  'camera',
  'chart-column',
  'check',
  'chevron-down',
  'chevron-left',
  'chevron-right',
  'clipboard-list',
  'clock',
  'copy',
  'dumbbell',
  'file-text',
  'flame',
  'info',
  'key',
  'pause',
  'pencil',
  'piggy-bank',
  'play',
  'plus',
  'qr-code',
  'refresh-cw',
  'search',
  'settings',
  'sliders-horizontal',
  'square-check',
  'star',
  'trash-2',
  'user-round',
  'x'
];

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const version = require('lucide/package.json').version;

const pascal = (name) => name.split('-').map((part) => part[0].toUpperCase() + part.slice(1)).join('');

// An IconNode entry is [tag, attributes]. `key` is a renderer concern in the framework
// bindings and never belongs in the emitted markup.
function element([tag, attributes]) {
  const pairs = Object.entries(attributes)
    .filter(([name]) => name !== 'key')
    .map(([name, value]) => ` ${name}="${String(value).replace(/"/g, '&quot;')}"`)
    .join('');
  return `<${tag}${pairs}/>`;
}

const entries = [...ICONS].sort().map((name) => {
  const node = lucide[pascal(name)];
  if (!Array.isArray(node)) throw new Error(`lucide ${version} has no icon named '${name}'`);
  return `  '${name}': '${node.map(element).join('')}',`;
});

const output = `// Generated by scripts/generate-icons.mjs from lucide ${version}. Do not edit by hand.
// Add a name to that script's ICONS list and run \`npm run icons\` instead.
//
// Only the geometry is stored. \`src/app/icons.ts\` owns the wrapper - one stroke width, one
// set of caps and joins, one accessibility rule - so an icon cannot arrive half-standardized.

export const ICON_PATHS = {
${entries.join('\n')}
} as const;

export type IconName = keyof typeof ICON_PATHS;
`;

const target = path.join(root, 'src/app/icon-paths.ts');
fs.writeFileSync(target, output);
console.log(`Wrote ${ICONS.length} icons from lucide ${version} to src/app/icon-paths.ts`);
